;;global key name MUST NAMED with prefix 'gl.'
 
[global]
gl.zone.err.title = "Error Message:"
gl.dialog.err.title = "Error Message"
gl.dialog.title = "Message"

gl.btn.submit = "Submit"
gl.btn.cancel = "Cancel"
gl.btn.delete = "Delete"
gl.btn.modify = "Modify"
gl.btn.update = "Update"
gl.btn.browse = "Browse"
gl.btn.close = "Close"
gl.btn.back = "Back"
gl.btn.download = "Download"
gl.btn.confirm = "Yes"

gl.option.choose = "Please choose"
gl.option.none = "None"

;;gl.txt.add.success = "Add success."
gl.txt.update.success = "Data has been updated."
;;gl.txt.delete.success = "Delete success."
gl.txt.nodata = "No data"
gl.txt.none = "N/A"
gl.txt.on = "On"
gl.txt.off = "Off"
gl.txt.confirm = "Confirmation"

gl.grid.recordtext = "Record {0} - {1} of {2}",
gl.grid.pgtext = "Page {0} of {1}"
gl.grid.loadtext = "Loading..."

gl.sms.progress.msg = "Sending command to the controller and waiting for replay.<br />This could be taken up to 5 minutes, please be patient."
gl.sms.progress.noexists = "SMS Function \"{0}\" is not exists."
gl.sms.progress.debug = "[SMS Debuging]<br />{0}"
gl.sms.progress.err.send = "Error occurs when sending command.<br />The cause is: {0}"
gl.sms.progress.err.send.timeout = "Progress timeout, the command might not be completed.<br />Please try again."
gl.sms.progress.err.unknown = "Unknown" 
gl.sms.progress.err.timeout = "Progress timeout."
gl.sms.progress.err.network = "Network communication problem."
gl.sms.progress.err.sender = "SMS sender problem."

gl.valimsg.required = "This field is required"
gl.valimsg.minlength = "At least {0} characters are accepted"
gl.valimsg.maxlength = "Less than {0} characters are accepted"
gl.valimsg.number = "Number only"
gl.valimsg.digit = "Digits only"
gl.valimsg.email = "Email address must be in the format of name@domain.com"
gl.valimsg.select = "Please select a valid option item"
gl.valimsg.repass = "Passwords are not matched"